"""init

Revision ID: 9afb4139df82
Revises: 
Create Date: 2025-12-03 10:35:30.025477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9afb4139df82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_permissions_id'), 'permissions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_permissions_name'), 'permissions', ['name'], unique=True, schema='public')
    op.create_table('riders',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    schema='public'
    )
    op.create_index(op.f('ix_public_riders_id'), 'riders', ['id'], unique=False, schema='public')
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_roles_id'), 'roles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_roles_name'), 'roles', ['name'], unique=True, schema='public')
    op.create_table('tenant_permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_permissions_action'), 'tenant_permissions', ['action'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_permissions_id'), 'tenant_permissions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_permissions_name'), 'tenant_permissions', ['name'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenant_permissions_resource'), 'tenant_permissions', ['resource'], unique=False, schema='public')
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('billing_tier', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_schema_name'), 'tenants', ['schema_name'], unique=True, schema='public')
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'id'),
    sa.UniqueConstraint('refresh_token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='public')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['public.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', 'id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_role_permissions_id'), 'role_permissions', ['id'], unique=False, schema='public')
    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('global_user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_user_id', sa.UUID(), nullable=True),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['global_user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_token_blocklist_id'), 'token_blocklist', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False, schema='public')
    op.create_index(op.f('ix_public_token_blocklist_tenant'), 'token_blocklist', ['tenant'], unique=False, schema='public')
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['public.permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', 'id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_permissions_id'), 'user_permissions', ['id'], unique=False, schema='public')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.String(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_roles_id'), 'user_roles', ['id'], unique=False, schema='public')
    op.create_table('user_tenants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id', 'id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_tenants_id'), 'user_tenants', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_tenants_id'), table_name='user_tenants', schema='public')
    op.drop_table('user_tenants', schema='public')
    op.drop_index(op.f('ix_public_user_roles_id'), table_name='user_roles', schema='public')
    op.drop_table('user_roles', schema='public')
    op.drop_index(op.f('ix_public_user_permissions_id'), table_name='user_permissions', schema='public')
    op.drop_table('user_permissions', schema='public')
    op.drop_index(op.f('ix_public_token_blocklist_tenant'), table_name='token_blocklist', schema='public')
    op.drop_index(op.f('ix_public_token_blocklist_jti'), table_name='token_blocklist', schema='public')
    op.drop_index(op.f('ix_public_token_blocklist_id'), table_name='token_blocklist', schema='public')
    op.drop_table('token_blocklist', schema='public')
    op.drop_index(op.f('ix_public_role_permissions_id'), table_name='role_permissions', schema='public')
    op.drop_table('role_permissions', schema='public')
    op.drop_index(op.f('ix_public_refresh_tokens_id'), table_name='refresh_tokens', schema='public')
    op.drop_table('refresh_tokens', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_tenants_schema_name'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_tenant_permissions_resource'), table_name='tenant_permissions', schema='public')
    op.drop_index(op.f('ix_public_tenant_permissions_name'), table_name='tenant_permissions', schema='public')
    op.drop_index(op.f('ix_public_tenant_permissions_id'), table_name='tenant_permissions', schema='public')
    op.drop_index(op.f('ix_public_tenant_permissions_action'), table_name='tenant_permissions', schema='public')
    op.drop_table('tenant_permissions', schema='public')
    op.drop_index(op.f('ix_public_roles_name'), table_name='roles', schema='public')
    op.drop_index(op.f('ix_public_roles_id'), table_name='roles', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_index(op.f('ix_public_riders_id'), table_name='riders', schema='public')
    op.drop_table('riders', schema='public')
    op.drop_index(op.f('ix_public_permissions_name'), table_name='permissions', schema='public')
    op.drop_index(op.f('ix_public_permissions_id'), table_name='permissions', schema='public')
    op.drop_table('permissions', schema='public')
    # ### end Alembic commands ###
